### PR TITLE
add osxarm

### PR DESCRIPTION
**Pull request by ngam**
adding osx-arm64
needed/wanted by: https://github.com/conda-forge/staged-recipes/pull/17580

### CODE REVIEW

**Comment by ngam** [comment]
re https://github.com/conda-forge/dmlc-feedstock/pull/5

@hcho3, do you have an interest in joining the mxnet maintainership?

**Comment by jakirkham** [comment]
Can we add `dmlc` to [this list]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt )? That's usually how we handle macOS ARM migrations.

**Comment by ngam** [comment]
> Can we add `dmlc` to [this list](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt)? That's usually how we handle macOS ARM migrations.

I know, but I thought I would just add it directly. Is there a particular problem with adding it directly?

**Comment by ngam** [comment]
You cans see previously 34d009c the support was added manually..

**Comment by jakirkham** [comment]
No problem, but it is useful to communicate this to the bot so we have this tracked going forward.

**Comment by ngam** [comment]
> 

That was my question actually --- does the bot not track the ones that were done manually?

**Comment by jakirkham** [comment]
It does not.

**Comment by ngam** [comment]
And yes, I often defer to the bot when there are some dependencies that require attention

**Comment by chyunsu3** [comment]
@ngam Sorry, I am not interested. My hands are full as it is already.

**Review by hcho3 — APPROVED** [review]

**Comment by ngam** [comment]
Thanks @hcho3! I noticed this package might be missing some components (or maybe they should be in other packages) needed by mxnet, so I will be coming again to highlight those. 

For now, this could safely be merged. Thanks team!

**Pull request merged**
